### ISSUE TITLE
limiter.check not returns negative number

### ISSUE THREAD

**Issue by sm2017** [dex4er/js-sliding-window-rate-limiter#9]
In document we have

> ## check
> 
> ```js
> const usage = await limiter.check(key, limit)
> ```
> 
> Checks current usage for key. If usage is above limit, it returns a negative number with current > usage. Throws an error if has occurred.

it don't return negative number just return limit

 ```js
const { SlidingWindowRateLimiter } = require('sliding-window-rate-limiter');

const ATTEMPTS = 3;
const INTERVAL = 60;

const limiter = SlidingWindowRateLimiter.createLimiter({
  interval: INTERVAL,
}).on('error', err => {
  console.error(err);
});

const key = 'limiter';


(async () => {
  await limiter.reserve(key, ATTEMPTS);
  await limiter.reserve(key, ATTEMPTS);
  await limiter.reserve(key, ATTEMPTS);
  await limiter.reserve(key, ATTEMPTS);
  const check = await limiter.check(key, ATTEMPTS);// returns 3 instead of -3
  console.log(check);
})();

```

**Comment by duyleekun** [comment]
Doc is wrong. IMO, check shouldn't return negative nor  throw.

**Comment by sm2017** [comment]
OK

**Comment by dex4er** [comment]
@duyleekun @sm2017 Doc is correct: `check` returns negative when current usage is **above** limit.

So you can provoke negative value with:

```js
  const check = await limiter.check(key, ATTEMPTS - 1) // returns -2
```
